NOID:
  noid_path: "/usr/local/bin/noid"
  db_path: "/home/srappel/noid_wrapper" # Default is "." which will look in ./NOID

Logging:
  level: "DEBUG"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
